### ISSUE TITLE
Case sensitivity  on parsing org flag

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/asnmap#1]
Hey, 
When using the script and parsing the -org flag using a example such as google, results are not returned if you use "google" however "GOOGLE" does parse ranges.
I suggest the script uppercases org flag input if api.asnmap.sh uses this format. 
:)

**Comment by ehsandeep** [comment]
Thanks for this feature request, it's known behaviour and planned to support case insensitive input for org.

Thanks again @PR3R00T for creating this issue.

**Comment by ehsandeep** [comment]
@PR3R00T this is now fixed.
