### ISSUE TITLE
unable to add API key for asnmap

### ISSUE THREAD

**Issue by atharvak95** [projectdiscovery/asnmap#289]
Hello guys,

am trying to add my API key into asnmap. but I keep getting this error -
flag provided but not defined: -auth

check screenshot
<img width="319" alt="ASNmap" src="https://github.com/projectdiscovery/asnmap/assets/85757680/1e086c74-320d-41ac-8038-14185002fc33">

**Comment by ehsandeep** [comment]
@atharvak95 make sure to update to new release - https://github.com/projectdiscovery/asnmap/releases/tag/v1.1.0
