### ISSUE TITLE
output not being writen to stdout with -c -silent

### ISSUE THREAD

**Issue by nickpending** [projectdiscovery/asnmap#302]
For example:

`asnmap -a AS20001 -c -silent`
`asnmap -a AS20001 -c`

vs

`asnmap -a AS20001 -c -silent -o myoutput.txt`

The former produces no output and the latter works as intended. Previously, both worked as expected. The first would output CSV data to stdout and the second would write CSV data to a file.

I *think* this might be due to a recent change in runner.go (line 61) but haven't done enough testing to confirm.

**Comment by dogancanbakir** [comment]
You're right; the behavior has changed with https://github.com/projectdiscovery/asnmap/pull/183.
