### ISSUE TITLE
asnmap unreliable

### ISSUE THREAD

**Issue by mr-pmillz** [projectdiscovery/asnmap#31]
The underlying API that asnmap uses is unstable, api.asnmap.sh/api/v1/asnmap?ip=X.X.X.X

the endpoint hangs and doesn't return results.
The tool itself is awesome when it works properly however it seems that the API is having issues.

![image](https://user-images.githubusercontent.com/58376398/203439219-4116ab01-f523-4282-ad73-7c6427f84c02.png)

I debugged through the code base and the code looks really good, however the API seems to be having issues and is unresponsive.

I also tried changing my IP address but am still getting the same errors.
![image](https://user-images.githubusercontent.com/58376398/203440012-1e3fa933-8849-4bfe-bd3d-a7df3559a925.png)

```shell
[FTL] unexpected end of JSON input
```
essentially, the API doesn't respond resulting in an http request timeout in the call to c.makeRequest() in client.go on line 116
https://github.com/projectdiscovery/asnmap/blob/main/libs/client.go#L116

Do you experience the same results?
@ehsandeep

**Comment by ehsandeep** [comment]
@mr-pmillz, some heavy automation is going on; we will soon implement a rate limit on the server and adopt the client accordingly.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/8293321/203838272-eb01fb92-4d2f-4e30-973b-84389f4c1bf0.png">
