### ISSUE TITLE
asnmap command is not recognizing please do tell is it the problem for path 

### ISSUE THREAD

**Issue by Satendrapatel980** [projectdiscovery/asnmap#327]
```
┌──(kali㉿kali)-[~]
└─$ go install github.com/projectdiscovery/asnmap/cmd/asnmap@latest
                                                                                                              
┌──(kali㉿kali)-[~]
└─$ asnmap -h  
```

**Comment by Prahladsolanki** [comment]
> ```
> ┌──(kali㉿kali)-[~]
> └─$ go install github.com/projectdiscovery/asnmap/cmd/asnmap@latest
>                                                                                                               
> ┌──(kali㉿kali)-[~]
> └─$ cp ~/go/bin/asnmap  /bin/      

> ```

**Comment by dogancanbakir** [comment]
What's the output of `go env`?

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issues persist.
