### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by taku65maku** [projectdiscovery/asnmap#397]
hlo sir sandep bhai ,
when i try to innsall asnmap and mapcidr  . i always get same error,
package errors is not in std (/usr/lib/go/bin/src/errors)
package bufio is not in std (/usr/lib/go/bin/src/bufio)
package crypto/tls is not in std (/usr/lib/go/bin/src/crypto/tls)
package encoding/json is not in std (/usr/lib/go/bin/src/encoding/json)
 plzz help

**Comment by taku65maku** [comment]
and my go env
export PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/rahul/go/bin
#export GOBIN=$GOPATH/bin
#export PATH=$PATH:$GOBIN
export GOROOT=/usr/lib/go/bin

**Comment by dogancanbakir** [comment]
Your environment variables seem to be set incorrectly. Here's how you should set them:
1. `GOROOT` should point to the location where Go is installed. For a default installation, this is usually `/usr/local/go`.
2. `GOPATH` should point to your workspace directory, not the bin directory. If your workspace is in `/home/rahul/go`, then `GOPATH` should be set to that.
3. `GOBIN` should be set to the bin directory inside your workspace, i.e., `$GOPATH/bin`.
