### ISSUE TITLE
RFE: add proxy support

### ISSUE THREAD

**Issue by bill-e-ghote** [projectdiscovery/asnmap#4]
For those who are connected to corporate networks with required proxy to access the Internet.

```console
   -p, -proxy       list of proxy to use (comma separated or file input)
```

Should support:
- http
- socks5

**Comment by Gitgody** [comment]
> For those who are connected to corporate networks with required proxy to access the Internet.
> 
> 
> 
> ```console
> 
>    -p, -proxy       list of proxy to use (comma separated or file input)
> 
> ```
> 
> 
> 
> Should support:
> 
> - http
> 
> - socks5

Exit
