### ISSUE TITLE
Release 1.0.1 without assets

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/asnmap#86]
## Description
Release 1.0.1 couldn't correctly generate assets due to a git commit hash mismatch. A new release, 1.0.2, should be generated after the `dev` => `main` merge. Todo:
- [x] PR `dev` to `main`
- [x] Tag and release `v1.0.2`

Ref: https://github.com/projectdiscovery/asnmap/actions/runs/4323004122

**Comment by ehsandeep** [comment]
Fixed with https://github.com/projectdiscovery/asnmap/pull/87
